// <auto-generated />
namespace DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class _0second0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0second0));
        
        string IMigrationMetadata.Id
        {
            get { return "201911071311519_0second0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
